# -*- coding: utf-8 -*-
"""HD01_20241201_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3W8rnqgGn1alk5HCyV6WtgcaOYulsU5

###HD01・header設定
"""

# hd01.py
# @title StableDiffusion・AddonsManager初期設定 {"form-width":"400px"}

# @markdown #1. StableDiffusion Manager側初期設定値

# @markdown StableDifusion WenUI AUTOMATIC1111 レポジトリアドレス
repo_url = "https://github.com/AUTOMATIC1111/stable-diffusion-webui.git" # @param {"type":"string"}
# @markdown StableDiffusionのコピー先
repo_folder = "/content/stable-diffusion-webui" # @param {"type":"string"}

# @markdown CivitAI API Keyを入れておくと、CheckPointをダウンロードできるようになります。
CivitAI_api_key = "512f7b6deddc348158cc53ae5d8642b3" # @param {"type":"string","placeholder":"CivitAIのAPI KEYを入力してください"}
# @markdown たくさんCheckpointがある場合、起動a時に選択するものを指定できます。
init_checkpoint = "waiNSFWIllustrious_v70_974429.safetensors" # @param {"type":"string","placeholder":"初期checkpointを入力"}
# @markdown Google Driveにフォルダを作成し、StableDiffusionの各種設定ファイルをバックアップします。
drive_path = "/content/drive/MyDrive/SD_XL_webUI_data/" # @param {"type":"string","placeholder":"StableDiffusionバックアップ用パス"}
# @markdown Google Driveに保存されているStableDiffusionバックアップフォルダを完全消去し、システムをリセットします。
system_reset = False # @param {"type":"boolean","placeholder":"システムリセット"}

# @markdown #3. Debug_Helper

# @markdown True時、Debug_Helperを有効化します。
flg_debug = True # @param {"type":"boolean"}

# @title 各種オブジェクトのエクスポート準備設定
# hd01.py
import os
import shutil
import requests
import importlib
import urllib.request as urllib_request
import subprocess
import ipywidgets as widgets
from IPython.display import display
from packaging import version
from google.colab import drive

os = os
shutil = shutil
requests = requests
importlib = importlib
urllib_request = urllib_request
subprocess = subprocess
widgets = widgets
display = display
version = version
drive = drive

# debug_helperセットアップ
# @title debug_helper設定
# 1. Google Driveをマウント
from google.colab import drive
drive.mount('/content/drive')

# 2. ライブラリのパスを追加
import sys
sys.path.append('/content/drive/My Drive/ColabLibraries')

import debug_helper
importlib.reload(debug_helper)
from debug_helper import initialize_debugger
debugger = initialize_debugger( debug = flg_debug )

# @title allによる名前空間のエクスポート設定
__all__ = [ "subprocess", "os", "shutil", "importlib", "urllib_request", "widgets", "display", "version", "drive",
            "repo_url", "repo_folder", "CivitAI_api_key", "init_checkpoint", "drive_path", "system_reset", "flg_debug",
            "debugger", "initialize_debugger" ]